name: Windows

on:
  pull_request:
    types: [main]
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./Homework

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
      matrix:
        platform: [windows]
        build_type: [Release]
    env:
      PARALLEL: -j 2
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Clone OpenCV
        run: git clone https://github.com/opencv/opencv

      - name: Configure OpenCV
        run: cmake -H"." -B"build/${{ matrix.platform }}" -DCMAKE_INSTALL_PREFIX=install
        working-directory: ./Homework/opencv
      
      - name: Build OpenCV
        run: cmake --build "build/${{ matrix.platform }}" --target INSTALL --config ${{ matrix.build_type }} ${{ env.PARALLEL }}
        working-directory: ./Homework/opencv

      - name: Set OpenCV path
        run: ./setup_vars_opencv4.cmd
        working-directory: ./Homework/opencv/build

      - name: Configure
        run: cmake -H"." -B"build/${{ matrix.platform }}"
        working-directory: ./Homework/opencv

      - name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
        run: cmake --build "build/${{ matrix.platform }}" --target ALL_BUILD --config ${{ matrix.build_type }} ${{ env.PARALLEL }}
        working-directory: ./Homework/opencv
